# Generated by Django 5.2 on 2025-04-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dateOfBirth',
            new_name='birthDate',
        ),
    ]
